### PR TITLE
fixes clog details and adds cargo third part subcommands

### PR DESCRIPTION
**Pull request by kbknapp**

### CODE REVIEW

**Comment by landesfeind** [comment]
Hi, there is a typo at `https://github.com/killercup/carg-edit` (notice the missing "o")

**Comment by kbknapp** [comment]
My mistake, thanks for pointing this out! I'll fix and rebase.

**Comment by kud1ing** [comment]
Lot of cargo. thanks.

**Comment by N-006** [comment]
Why no cargo-watch? :)

**Pull request merged**
