### PR TITLE
Added cargo-modules

### PR DESCRIPTION
**Pull request by regexident**

### CODE REVIEW

**Comment by kud1ing** [comment]
Thanks. Except for the second difference where 2 crate links are removed.
Was that intentional?

**Comment by regexident** [comment]
> 2 crate links are removed in the second difference. Was that intentional?

Well yeah. Kinda. Given that none of the other cargo plugins had those second links I though those probably were redundant remnants of previous edit, or something, not noticing that the links differed.
Anyway, I fixed it and added the missing crate links for all other cargo plugins.

**Comment by kud1ing** [comment]
Thank you

**Comment by regexident** [comment]
Also, ei guude wie! ✋  😃  Have we met yet?
Either way you should really show up at [Rust Rhein-Main](http://meetup.com/Rust-Rhein-Main) some time! 👍

**Comment by kud1ing** [comment]
:)
Yes, i've considered the gathering in Textor, but couldn't make it.
Next time.

**Pull request merged**
