### PR TITLE
Add dylanmckay/protocol library

### PR DESCRIPTION
**Pull request by dylanmckay**
The library is used to define packet-based protocol definitions.

[library](https://github.com/dylanmckay/protocol).

### CODE REVIEW

**Comment by kud1ing** [comment]
Hi, thank you.
I'd prefer to have this under "Network programming" - maybe under the subsection "Low level". What do you think?

**Comment by dylanmckay** [comment]
Good idea, I'll fix that.

**Comment by dylanmckay** [comment]
@kud1ing fixed :)

**Comment by kud1ing** [comment]
Thank you.

**Pull request merged**
