### PR TITLE
Add an .md file that attach stars count and last updated date

### PR DESCRIPTION
**Pull request by chaconnewu**
Added a separate file that is a complete clone of the original README.md file, attaching the number of stars as well as last pushed date for each GitHub repositories included in the curated list. The date was collected through GitHub API (just now). And I can update the file regularly or as needed.

Let me know if you find it interesting. Thanks!

View the fille directly at:
https://github.com/chaconnewu/dashboard_for_awesomes/blob/master/awesomes/awesome_rust_with_repo_info.md

### CODE REVIEW

**Comment by kud1ing** [comment]
Nice scripting there. :) An overview of such stats is certainly interesting.

OTOH i find it's in the nature of a project like this that its content tends to overwhelm. We have many entries. I'd like to keep each entry as minimalistic as possible because i fear adding to each of them increases the debt of overwhelm.

Thank you, and keep up the good work.

**Comment by chaconnewu** [comment]
Hi @kud1ing, thanks a lot for the feedback. I want to point out that this is a separate file, which will not overwrite your existing one. So users will have a minimalistic experience by default. If they want more info, they can browse the one I generated. What do you think?

**Comment by kud1ing** [comment]
Yes, i understand.

In the beginning i'd generated the markdown file from a Python script. That made sure that format was correct everywhere and that you could have "duplicate" entries in different places without actually duplicating the information. It turned out that people assumed markdown files to be a source and not a product. So this caused some problems.

I feel that the informational scope of this project should be kept small. But it think there is a lot of room for interesting projects like yours for mixing in additional (live) data.

**Comment by chaconnewu** [comment]
Thanks a lot for your response @kud1ing! Sorry that I have many questions :). But I'm a HCI researcher, trying to understand and improve curation practice (my profile: https://scholar.google.com/citations?user=1TNPqLMAAAAJ&hl=en). So I'm very interested in your experience & perception of the curation practice as well. 

I'm wondering what did you mean by "people assumed markdown files to be a source and not a product"? And what problems it caused?

You are definitely free to answer me or not.

**Comment by kud1ing** [comment]
What i meant is, that people had send pull requests where the generated markdown file was modified, instead of the script.

**Pull request closed without merging**
